version: '3.3'

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: test
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
        - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  grails:
    image: oleg-tech-assessment/build:0.1
    ports:
     - 8080:8080

volumes:
  my-datavolume:
#clean: docker-compose rm -fv